# Generated by Django 3.2 on 2021-11-09 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999)])),
            ],
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(check=models.Q(('series__gte', 1000), ('series__lte', 9999)), name='series__value'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(check=models.Q(('number__gte', 1), ('number__lte', 999999)), name='number_value'),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('series', 'number')},
        ),
        migrations.AlterIndexTogether(
            name='card',
            index_together={('series', 'number')},
        ),
    ]
