# Generated by Django 3.2 on 2021-11-10 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Карта', 'verbose_name_plural': 'Карты'},
        ),
        migrations.AddField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='card',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterIndexTogether(
            name='card',
            index_together=set(),
        ),
    ]
